# Generated by Django 4.0.5 on 2022-06-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='public_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
