# Generated by Django 4.0.5 on 2022-06-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_comment_public_date_alter_post_public_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-public_date',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-public_date',)},
        ),
    ]
