# Generated by Django 4.0.5 on 2022-06-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
