# Generated by Django 4.0.5 on 2022-06-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
