# Generated by Django 4.0.5 on 2022-06-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('public_date', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
            options={
                'ordering': ('-public_date',),
            },
        ),
    ]
